// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/dushixiang/pika/internal/config"
	"github.com/dushixiang/pika/internal/handler"
	"github.com/dushixiang/pika/internal/repo"
	"github.com/dushixiang/pika/internal/service"
	"github.com/dushixiang/pika/internal/websocket"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp(logger *zap.Logger, db *gorm.DB, cfg *config.AppConfig) (*AppComponents, error) {
	userService := service.NewUserService(logger, cfg)
	oidcService := service.NewOIDCService(logger, cfg)
	gitHubOAuthService := service.NewGitHubOAuthService(logger, cfg)
	accountService := service.NewAccountService(logger, userService, oidcService, gitHubOAuthService, cfg)
	accountHandler := handler.NewAccountHandler(accountService)
	apiKeyService := service.NewApiKeyService(logger, db)
	propertyService := service.NewPropertyService(logger, db)
	metricService := service.NewMetricService(logger, db, propertyService)
	geoIPService, err := service.NewGeoIPService(logger, cfg)
	if err != nil {
		return nil, err
	}
	agentService := service.NewAgentService(logger, db, apiKeyService, metricService, geoIPService)
	manager := websocket.NewManager(logger)
	monitorService := service.NewMonitorService(logger, db, manager)
	tamperRepo := repo.NewTamperRepo(db)
	tamperService := service.NewTamperService(logger, tamperRepo, manager)
	ddnsConfigRepo := repo.NewDDNSConfigRepo(db)
	ddnsRecordRepo := repo.NewDDNSRecordRepo(db)
	ddnsService := service.NewDDNSService(logger, ddnsConfigRepo, ddnsRecordRepo, propertyService, manager)
	agentHandler := handler.NewAgentHandler(logger, agentService, metricService, monitorService, tamperService, ddnsService, manager)
	apiKeyHandler := handler.NewApiKeyHandler(logger, apiKeyService)
	notifier := service.NewNotifier(logger)
	alertService := service.NewAlertService(logger, db, propertyService, notifier)
	alertHandler := handler.NewAlertHandler(logger, alertService)
	propertyHandler := handler.NewPropertyHandler(logger, propertyService, notifier)
	monitorHandler := handler.NewMonitorHandler(logger, monitorService, agentService)
	tamperHandler := handler.NewTamperHandler(logger, tamperService)
	dnsProviderHandler := handler.NewDNSProviderHandler(logger, propertyService)
	ddnsHandler := handler.NewDDNSHandler(logger, ddnsService)
	appComponents := &AppComponents{
		AccountHandler:     accountHandler,
		AgentHandler:       agentHandler,
		ApiKeyHandler:      apiKeyHandler,
		AlertHandler:       alertHandler,
		PropertyHandler:    propertyHandler,
		MonitorHandler:     monitorHandler,
		TamperHandler:      tamperHandler,
		DNSProviderHandler: dnsProviderHandler,
		DDNSHandler:        ddnsHandler,
		AgentService:       agentService,
		MetricService:      metricService,
		AlertService:       alertService,
		PropertyService:    propertyService,
		MonitorService:     monitorService,
		ApiKeyService:      apiKeyService,
		TamperService:      tamperService,
		DDNSService:        ddnsService,
		WSManager:          manager,
	}
	return appComponents, nil
}

// wire.go:

// AppComponents 应用组件
type AppComponents struct {
	AccountHandler     *handler.AccountHandler
	AgentHandler       *handler.AgentHandler
	ApiKeyHandler      *handler.ApiKeyHandler
	AlertHandler       *handler.AlertHandler
	PropertyHandler    *handler.PropertyHandler
	MonitorHandler     *handler.MonitorHandler
	TamperHandler      *handler.TamperHandler
	DNSProviderHandler *handler.DNSProviderHandler
	DDNSHandler        *handler.DDNSHandler

	AgentService    *service.AgentService
	MetricService   *service.MetricService
	AlertService    *service.AlertService
	PropertyService *service.PropertyService
	MonitorService  *service.MonitorService
	ApiKeyService   *service.ApiKeyService
	TamperService   *service.TamperService
	DDNSService     *service.DDNSService

	WSManager *websocket.Manager
}
